module.exports = {
    //入口文件
    entry:'./src/js/index.js',
    output:{//指定输出的位置
        path:'./build',//指定输出的文件夹
        filename:'bundle.js'//指定输出的文件名
    },
    //配置模块加载器
    module:{
        loaders:[
            {
                test:/\.js$/,
                loader:'babel'
            },
            {
                test:/\.css$/,
                loader:'style!css'
            },
            {
                test:/(\.eot|svg|ttf|woff|woff2$)/,
                loader:'url'
            }
        ]
    }
}